### ISSUE TITLE
Add support for ACR rbac permissions when using custom container runtime

### ISSUE THREAD

**Issue by julienbourgoin-maif** [Azure/Azure-Spring-Apps#44] opened 2023-04-05 10:20 UTC
**Is your feature request related to a problem? Please describe.**

I tried to create an app using a custom container runtime.
I gave to this app a system assigned identity.
I gave to this identity, a role assignment AcrPull on my Azure Container Registry.

When I tried to create a deployment on this app, I used this kind of azure cli command:

```shell
az spring app deployment create \
   -g <rgname> -s <servicename> \
   --app <appname> \
   --name <deploymentname> \
   --container-image <imagename>:<version> \
   --container-registry <acrname>.azurecr.io
```

Unfortunately, spring apps was not able to pull my docker image on the ACR.

It seems that ASA is not compatible with ACR rbac.
To make it work, I had to add the following args to my command:

```shell
   --registry-username <acrusername> \
   --registry-password <password> \
```

And the role assignment AcrPull is useless for the moment.

**Describe the solution you'd like**

I should be able to use the app identity to pull my docker images in ACR.
I should not have to use a username / password to do that.

**Comment by julienbourgoin-maif** [comment] 2023-04-05 10:21
Just realized it's a duplicate of https://github.com/Azure/Azure-Spring-Apps/issues/42

**Comment by selvasingh** [comment] 2023-05-10 13:52
Spoke with @julienbourgoin-maif and concluded that this is a duplicate of #42 .. Julien will continue the conversation in issue #42

**Closed as completed by selvasingh** 2023-05-10 13:52 UTC
