### ISSUE TITLE
Enterprise Tier from Azure Market Place: wizard configure Basic Tier

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/Azure-Spring-Apps#19] opened 2022-12-12 11:03 UTC
Go to the Azure Market Place, select Azure Spring Apps Enterprise  , once you land on the Azure Portal, the service is configured with Basic Tier on the screen whereas it should be Enterprise Tier

**Expected behavior**
In the Azure Portal , Enterprise Tier should be selected by default in this scenario

**Comment by seanli1988** [comment] 2022-12-13 01:29
basic tier is the default due to low price entry. closing this issue as it's by design.

**Closed by seanli1988** 2022-12-13 01:29 UTC
Labels: bug
